apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service-1
  name: service-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-1
  template:
    metadata:
      labels:
        app: service-1
        segment: backend
    spec:
      containers:
      - image: sample-app:latest
        imagePullPolicy: Never
        name: app
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-1
  name: service-1
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: service-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service-2
  name: service-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-2
  template:
    metadata:
      labels:
        app: service-2
        segment: backend
    spec:
      containers:
      - image: sample-app:latest
        imagePullPolicy: Never
        name: app
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-2
  name: service-2
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: service-2
