apiVersion: v1
kind: ServiceAccount
metadata:
  name: faros
  labels:
    app: faros
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: faros-reader
  labels:
    app: faros
rules:
  - apiGroups: [""]
    resources: ["services", "secrets"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [ "gateway.networking.k8s.io" ]
    resources: [ "gatewayclasses", "gateways", "httproutes" ]
    verbs: [ "get", "watch", "list" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-services-secrets-ingresses-global
  labels:
    app: faros
subjects:
  - kind: ServiceAccount
    name: faros
    namespace: default
roleRef:
  kind: ClusterRole
  name: faros-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: faros
  labels:
    app: faros
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faros
  template:
    metadata:
      labels:
        app: faros
    spec:
      serviceAccountName: faros
      containers:
        - image: faros:latest
          imagePullPolicy: Never
          name: faros
          ports:
          - name: http
            containerPort: 80
            hostPort: 80

